-- Araç Þase-Plaka Yapýsý Migration
-- Mevcut Plaka verilerini korumak için önce verileri yedekle

-- 1. Geçici tablo oluþtur ve mevcut verileri yedekle
CREATE TEMP TABLE temp_arac_plakalar AS
SELECT "Id", "Plaka", "SaseNo" FROM "Araclar" WHERE "Plaka" IS NOT NULL;

-- 2. Araclar tablosuna yeni kolonlarý ekle
ALTER TABLE "Araclar" ADD COLUMN IF NOT EXISTS "AktifPlaka" character varying(15);
ALTER TABLE "Araclar" ADD COLUMN IF NOT EXISTS "SatisaAcik" boolean NOT NULL DEFAULT false;
ALTER TABLE "Araclar" ADD COLUMN IF NOT EXISTS "SatisFiyati" numeric(18,2);
ALTER TABLE "Araclar" ADD COLUMN IF NOT EXISTS "SatisaAcilmaTarihi" timestamp without time zone;
ALTER TABLE "Araclar" ADD COLUMN IF NOT EXISTS "SatisAciklamasi" text;

-- 3. SaseNo kolonu zorunlu hale getir (boþsa Plaka'dan doldur)
UPDATE "Araclar" SET "SaseNo" = "Plaka" WHERE "SaseNo" IS NULL OR "SaseNo" = '';
ALTER TABLE "Araclar" ALTER COLUMN "SaseNo" SET NOT NULL;

-- 4. AktifPlaka'yý mevcut Plaka'dan doldur
UPDATE "Araclar" SET "AktifPlaka" = "Plaka" WHERE "Plaka" IS NOT NULL;

-- 5. AracPlakalar tablosunu oluþtur
CREATE TABLE IF NOT EXISTS "AracPlakalar" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "AracId" integer NOT NULL,
    "Plaka" character varying(15) NOT NULL,
    "GirisTarihi" timestamp without time zone NOT NULL,
    "CikisTarihi" timestamp without time zone,
    "IslemTipi" integer NOT NULL DEFAULT 1,
    "Aciklama" character varying(500),
    "IslemTutari" numeric(18,2),
    "CariId" integer,
    "CreatedAt" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UpdatedAt" timestamp without time zone,
    "IsDeleted" boolean NOT NULL DEFAULT false,
    CONSTRAINT "PK_AracPlakalar" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AracPlakalar_Araclar_AracId" FOREIGN KEY ("AracId") REFERENCES "Araclar" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_AracPlakalar_Cariler_CariId" FOREIGN KEY ("CariId") REFERENCES "Cariler" ("Id") ON DELETE SET NULL
);

-- 6. Ýndexler
CREATE INDEX IF NOT EXISTS "IX_AracPlakalar_AracId" ON "AracPlakalar" ("AracId");
CREATE INDEX IF NOT EXISTS "IX_AracPlakalar_CariId" ON "AracPlakalar" ("CariId");
CREATE INDEX IF NOT EXISTS "IX_AracPlakalar_Plaka_CikisTarihi" ON "AracPlakalar" ("Plaka", "CikisTarihi") 
    WHERE "CikisTarihi" IS NULL AND "IsDeleted" = false;

-- SaseNo unique index
DROP INDEX IF EXISTS "IX_Araclar_SaseNo";
CREATE UNIQUE INDEX "IX_Araclar_SaseNo" ON "Araclar" ("SaseNo") WHERE "IsDeleted" = false;

-- 7. Mevcut plakalarý AracPlakalar tablosuna aktar
INSERT INTO "AracPlakalar" ("AracId", "Plaka", "GirisTarihi", "IslemTipi", "Aciklama", "CreatedAt", "IsDeleted")
SELECT "Id", "Plaka", COALESCE("CreatedAt", CURRENT_TIMESTAMP), 1, 'Mevcut kayýttan aktarýldý', CURRENT_TIMESTAMP, false
FROM temp_arac_plakalar
WHERE "Plaka" IS NOT NULL AND "Plaka" != ''
ON CONFLICT DO NOTHING;

-- 8. Eski Plaka index'ini kaldýr (varsa)
DROP INDEX IF EXISTS "IX_Araclar_Plaka";

-- 9. Migration geçmiþini güncelle
INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260326224724_AracSasePlakaYapisi', '10.0.5')
ON CONFLICT DO NOTHING;

-- Geçici tabloyu temizle
DROP TABLE IF EXISTS temp_arac_plakalar;
