-- CRM Modülü tablolarý - sadece eksik olanlar

-- Roller tablosuna Renk kolonu (IF NOT EXISTS)
ALTER TABLE "Roller" ADD COLUMN IF NOT EXISTS "Renk" text;

-- Bildirimler tablosu
CREATE TABLE IF NOT EXISTS "Bildirimler" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "KullaniciId" integer NOT NULL,
    "Baslik" character varying(200) NOT NULL,
    "Icerik" character varying(1000),
    "Tip" integer NOT NULL,
    "Oncelik" integer NOT NULL,
    "Okundu" boolean NOT NULL DEFAULT false,
    "OkunmaTarihi" timestamp without time zone,
    "IliskiliTablo" character varying(50),
    "IliskiliKayitId" integer,
    "Link" character varying(200),
    "SonGosterimTarihi" timestamp without time zone,
    "Tekrarli" boolean NOT NULL DEFAULT false,
    "CreatedAt" timestamp without time zone NOT NULL,
    "UpdatedAt" timestamp without time zone,
    "IsDeleted" boolean NOT NULL DEFAULT false,
    CONSTRAINT "PK_Bildirimler" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Bildirimler_Kullanicilar_KullaniciId" FOREIGN KEY ("KullaniciId") REFERENCES "Kullanicilar" ("Id") ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS "IX_Bildirimler_KullaniciId" ON "Bildirimler" ("KullaniciId");

-- DashboardWidgetlar tablosu
CREATE TABLE IF NOT EXISTS "DashboardWidgetlar" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "KullaniciId" integer NOT NULL,
    "WidgetKodu" character varying(50) NOT NULL,
    "Sira" integer NOT NULL DEFAULT 0,
    "Kolon" integer NOT NULL DEFAULT 0,
    "Genislik" integer NOT NULL DEFAULT 4,
    "Gorunur" boolean NOT NULL DEFAULT true,
    "Kucultulmus" boolean NOT NULL DEFAULT false,
    "Ayarlar" character varying(2000),
    "CreatedAt" timestamp without time zone NOT NULL,
    "UpdatedAt" timestamp without time zone,
    "IsDeleted" boolean NOT NULL DEFAULT false,
    CONSTRAINT "PK_DashboardWidgetlar" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_DashboardWidgetlar_Kullanicilar_KullaniciId" FOREIGN KEY ("KullaniciId") REFERENCES "Kullanicilar" ("Id") ON DELETE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS "IX_DashboardWidgetlar_KullaniciId_WidgetKodu" ON "DashboardWidgetlar" ("KullaniciId", "WidgetKodu");

-- EmailAyarlari tablosu
CREATE TABLE IF NOT EXISTS "EmailAyarlari" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "KullaniciId" integer,
    "SmtpSunucu" character varying(100) NOT NULL,
    "SmtpPort" integer NOT NULL,
    "SslKullan" boolean NOT NULL DEFAULT true,
    "Email" character varying(100) NOT NULL,
    "Sifre" character varying(100),
    "GonderenAdi" character varying(100),
    "Aktif" boolean NOT NULL DEFAULT true,
    "CreatedAt" timestamp without time zone NOT NULL,
    "UpdatedAt" timestamp without time zone,
    "IsDeleted" boolean NOT NULL DEFAULT false,
    CONSTRAINT "PK_EmailAyarlari" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_EmailAyarlari_Kullanicilar_KullaniciId" FOREIGN KEY ("KullaniciId") REFERENCES "Kullanicilar" ("Id") ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS "IX_EmailAyarlari_KullaniciId" ON "EmailAyarlari" ("KullaniciId");

-- WhatsAppAyarlari tablosu
CREATE TABLE IF NOT EXISTS "WhatsAppAyarlari" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "KullaniciId" integer,
    "Telefon" character varying(20) NOT NULL,
    "ApiKey" character varying(200),
    "WebhookUrl" character varying(200),
    "Aktif" boolean NOT NULL DEFAULT true,
    "CreatedAt" timestamp without time zone NOT NULL,
    "UpdatedAt" timestamp without time zone,
    "IsDeleted" boolean NOT NULL DEFAULT false,
    CONSTRAINT "PK_WhatsAppAyarlari" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_WhatsAppAyarlari_Kullanicilar_KullaniciId" FOREIGN KEY ("KullaniciId") REFERENCES "Kullanicilar" ("Id") ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS "IX_WhatsAppAyarlari_KullaniciId" ON "WhatsAppAyarlari" ("KullaniciId");

-- Mesajlar tablosu
CREATE TABLE IF NOT EXISTS "Mesajlar" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "GonderenId" integer NOT NULL,
    "AliciId" integer,
    "Konu" character varying(200) NOT NULL,
    "Icerik" text NOT NULL,
    "Tip" integer NOT NULL DEFAULT 0,
    "Durum" integer NOT NULL DEFAULT 1,
    "Okundu" boolean NOT NULL DEFAULT false,
    "OkunmaTarihi" timestamp without time zone,
    "UstMesajId" integer,
    "DisAlici" character varying(200),
    "CreatedAt" timestamp without time zone NOT NULL,
    "UpdatedAt" timestamp without time zone,
    "IsDeleted" boolean NOT NULL DEFAULT false,
    CONSTRAINT "PK_Mesajlar" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Mesajlar_Kullanicilar_GonderenId" FOREIGN KEY ("GonderenId") REFERENCES "Kullanicilar" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Mesajlar_Kullanicilar_AliciId" FOREIGN KEY ("AliciId") REFERENCES "Kullanicilar" ("Id") ON DELETE SET NULL,
    CONSTRAINT "FK_Mesajlar_Mesajlar_UstMesajId" FOREIGN KEY ("UstMesajId") REFERENCES "Mesajlar" ("Id") ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS "IX_Mesajlar_GonderenId" ON "Mesajlar" ("GonderenId");
CREATE INDEX IF NOT EXISTS "IX_Mesajlar_AliciId" ON "Mesajlar" ("AliciId");
CREATE INDEX IF NOT EXISTS "IX_Mesajlar_UstMesajId" ON "Mesajlar" ("UstMesajId");

-- Hatirlaticilar tablosu
CREATE TABLE IF NOT EXISTS "Hatirlaticilar" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "KullaniciId" integer NOT NULL,
    "Baslik" character varying(200) NOT NULL,
    "Aciklama" character varying(1000),
    "Tip" integer NOT NULL DEFAULT 0,
    "BaslangicTarihi" timestamp without time zone NOT NULL,
    "BitisTarihi" timestamp without time zone,
    "TumGun" boolean NOT NULL DEFAULT false,
    "TekrarTipi" integer NOT NULL DEFAULT 0,
    "TekrarAraligi" integer NOT NULL DEFAULT 1,
    "TekrarBitisTarihi" timestamp without time zone,
    "BildirimDakikaOnce" integer NOT NULL DEFAULT 15,
    "Durum" integer NOT NULL DEFAULT 0,
    "Renk" character varying(20) DEFAULT '#0d6efd',
    "CariId" integer,
    "CreatedAt" timestamp without time zone NOT NULL,
    "UpdatedAt" timestamp without time zone,
    "IsDeleted" boolean NOT NULL DEFAULT false,
    CONSTRAINT "PK_Hatirlaticilar" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Hatirlaticilar_Kullanicilar_KullaniciId" FOREIGN KEY ("KullaniciId") REFERENCES "Kullanicilar" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Hatirlaticilar_Cariler_CariId" FOREIGN KEY ("CariId") REFERENCES "Cariler" ("Id") ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS "IX_Hatirlaticilar_KullaniciId" ON "Hatirlaticilar" ("KullaniciId");
CREATE INDEX IF NOT EXISTS "IX_Hatirlaticilar_CariId" ON "Hatirlaticilar" ("CariId");

-- KullaniciCariler tablosu
CREATE TABLE IF NOT EXISTS "KullaniciCariler" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "KullaniciId" integer NOT NULL,
    "CariId" integer NOT NULL,
    "EkstreGorebilir" boolean NOT NULL DEFAULT true,
    "FaturaGorebilir" boolean NOT NULL DEFAULT true,
    "OdemeYapabilir" boolean NOT NULL DEFAULT false,
    "DuzenlemeYapabilir" boolean NOT NULL DEFAULT false,
    "Tip" integer NOT NULL DEFAULT 0,
    "Not" character varying(500),
    "CreatedAt" timestamp without time zone NOT NULL,
    "UpdatedAt" timestamp without time zone,
    "IsDeleted" boolean NOT NULL DEFAULT false,
    CONSTRAINT "PK_KullaniciCariler" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_KullaniciCariler_Kullanicilar_KullaniciId" FOREIGN KEY ("KullaniciId") REFERENCES "Kullanicilar" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_KullaniciCariler_Cariler_CariId" FOREIGN KEY ("CariId") REFERENCES "Cariler" ("Id") ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS "IX_KullaniciCariler_KullaniciId_CariId" ON "KullaniciCariler" ("KullaniciId", "CariId");
CREATE INDEX IF NOT EXISTS "IX_KullaniciCariler_CariId" ON "KullaniciCariler" ("CariId");

-- Migration geçmiþini güncelle
INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260326204037_CRMModulu', '10.0.5')
ON CONFLICT DO NOTHING;
