// <auto-generated />
using System;
using CRMFiloServis.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CRMFiloServis.Web.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CRMFiloServis.Shared.Entities.Arac", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aktif")
                        .HasColumnType("boolean");

                    b.Property<int>("AracTipi")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("KaskoBitisTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("KmDurumu")
                        .HasColumnType("integer");

                    b.Property<int>("KoltukSayisi")
                        .HasColumnType("integer");

                    b.Property<string>("Marka")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Model")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("ModelYili")
                        .HasColumnType("integer");

                    b.Property<string>("MotorNo")
                        .HasColumnType("text");

                    b.Property<DateTime?>("MuayeneBitisTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Notlar")
                        .HasColumnType("text");

                    b.Property<string>("Plaka")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<string>("Renk")
                        .HasColumnType("text");

                    b.Property<string>("SaseNo")
                        .HasColumnType("text");

                    b.Property<DateTime?>("TrafikSigortaBitisTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Plaka")
                        .IsUnique();

                    b.ToTable("Araclar");
                });

            modelBuilder.Entity("CRMFiloServis.Shared.Entities.AracMasraf", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("text");

                    b.Property<int>("AracId")
                        .HasColumnType("integer");

                    b.Property<bool>("ArizaKaynaklimi")
                        .HasColumnType("boolean");

                    b.Property<string>("BelgeNo")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("GuzergahId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("MasrafKalemiId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("MasrafTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ServisCalismaId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Tutar")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AracId");

                    b.HasIndex("GuzergahId");

                    b.HasIndex("MasrafKalemiId");

                    b.HasIndex("ServisCalismaId");

                    b.ToTable("AracMasraflari");
                });

            modelBuilder.Entity("CRMFiloServis.Shared.Entities.BankaHesap", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AcilisBakiye")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<bool>("Aktif")
                        .HasColumnType("boolean");

                    b.Property<string>("BankaAdi")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("HesapAdi")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("HesapKodu")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("HesapNo")
                        .HasColumnType("text");

                    b.Property<int>("HesapTipi")
                        .HasColumnType("integer");

                    b.Property<string>("Iban")
                        .HasMaxLength(34)
                        .HasColumnType("character varying(34)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Notlar")
                        .HasColumnType("text");

                    b.Property<string>("ParaBirimi")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<string>("SubeAdi")
                        .HasColumnType("text");

                    b.Property<string>("SubeKodu")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("HesapKodu")
                        .IsUnique();

                    b.ToTable("BankaHesaplari");
                });

            modelBuilder.Entity("CRMFiloServis.Shared.Entities.BankaKasaHareket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("text");

                    b.Property<int>("BankaHesapId")
                        .HasColumnType("integer");

                    b.Property<string>("BelgeNo")
                        .HasColumnType("text");

                    b.Property<int?>("CariId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("HareketTipi")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("IslemKaynak")
                        .HasColumnType("integer");

                    b.Property<string>("IslemNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("IslemTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Tutar")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BankaHesapId");

                    b.HasIndex("CariId");

                    b.HasIndex("IslemNo")
                        .IsUnique();

                    b.ToTable("BankaKasaHareketleri");
                });

            modelBuilder.Entity("CRMFiloServis.Shared.Entities.Cari", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Adres")
                        .HasColumnType("text");

                    b.Property<string>("CariKodu")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("CariTipi")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Notlar")
                        .HasColumnType("text");

                    b.Property<string>("Telefon")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Unvan")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VergiDairesi")
                        .HasColumnType("text");

                    b.Property<string>("VergiNo")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("YetkiliKisi")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CariKodu")
                        .IsUnique();

                    b.ToTable("Cariler");
                });

            modelBuilder.Entity("CRMFiloServis.Shared.Entities.Fatura", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("text");

                    b.Property<decimal>("AraToplam")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("CariId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Durum")
                        .HasColumnType("integer");

                    b.Property<string>("FaturaNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("FaturaTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FaturaTipi")
                        .HasColumnType("integer");

                    b.Property<decimal>("GenelToplam")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<decimal>("KdvOrani")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<decimal>("KdvTutar")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Notlar")
                        .HasColumnType("text");

                    b.Property<decimal>("OdenenTutar")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("VadeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CariId");

                    b.HasIndex("FaturaNo")
                        .IsUnique();

                    b.ToTable("Faturalar");
                });

            modelBuilder.Entity("CRMFiloServis.Shared.Entities.FaturaKalem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Birim")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal>("BirimFiyat")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FaturaId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<decimal>("KdvOrani")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<decimal>("KdvTutar")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("Miktar")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<int>("SiraNo")
                        .HasColumnType("integer");

                    b.Property<decimal>("ToplamTutar")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("FaturaId");

                    b.ToTable("FaturaKalemleri");
                });

            modelBuilder.Entity("CRMFiloServis.Shared.Entities.Guzergah", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aktif")
                        .HasColumnType("boolean");

                    b.Property<string>("BaslangicNoktasi")
                        .HasColumnType("text");

                    b.Property<decimal>("BirimFiyat")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("BitisNoktasi")
                        .HasColumnType("text");

                    b.Property<int>("CariId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GuzergahAdi")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("GuzergahKodu")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("Mesafe")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("Notlar")
                        .HasColumnType("text");

                    b.Property<int?>("TahminiSure")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CariId");

                    b.HasIndex("GuzergahKodu")
                        .IsUnique();

                    b.ToTable("Guzergahlar");
                });

            modelBuilder.Entity("CRMFiloServis.Shared.Entities.MasrafKalemi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aktif")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("Kategori")
                        .HasColumnType("integer");

                    b.Property<string>("MasrafAdi")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("MasrafKodu")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Notlar")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("MasrafKodu")
                        .IsUnique();

                    b.ToTable("MasrafKalemleri");
                });

            modelBuilder.Entity("CRMFiloServis.Shared.Entities.OdemeEslestirme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("text");

                    b.Property<int>("BankaKasaHareketId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("EslestirilenTutar")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("EslestirmeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FaturaId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BankaKasaHareketId");

                    b.HasIndex("FaturaId");

                    b.ToTable("OdemeEslestirmeleri");
                });

            modelBuilder.Entity("CRMFiloServis.Shared.Entities.ServisCalisma", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AracId")
                        .HasColumnType("integer");

                    b.Property<string>("ArizaAciklamasi")
                        .HasColumnType("text");

                    b.Property<bool>("ArizaOlduMu")
                        .HasColumnType("boolean");

                    b.Property<TimeSpan?>("BaslangicSaati")
                        .HasColumnType("interval");

                    b.Property<TimeSpan?>("BitisSaati")
                        .HasColumnType("interval");

                    b.Property<DateTime>("CalismaTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Durum")
                        .HasColumnType("integer");

                    b.Property<decimal?>("Fiyat")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("GuzergahId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int?>("KmBaslangic")
                        .HasColumnType("integer");

                    b.Property<int?>("KmBitis")
                        .HasColumnType("integer");

                    b.Property<string>("Notlar")
                        .HasColumnType("text");

                    b.Property<int>("ServisTuru")
                        .HasColumnType("integer");

                    b.Property<int>("SoforId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AracId");

                    b.HasIndex("GuzergahId");

                    b.HasIndex("SoforId");

                    b.ToTable("ServisCalismalari");
                });

            modelBuilder.Entity("CRMFiloServis.Shared.Entities.Sofor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Adres")
                        .HasColumnType("text");

                    b.Property<bool>("Aktif")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("EhliyetGecerlilikTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EhliyetNo")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("IseBaslamaTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Notlar")
                        .HasColumnType("text");

                    b.Property<string>("SoforKodu")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("TcKimlikNo")
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)");

                    b.Property<string>("Telefon")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SoforKodu")
                        .IsUnique();

                    b.ToTable("Soforler");
                });

            modelBuilder.Entity("CRMFiloServis.Shared.Entities.AracMasraf", b =>
                {
                    b.HasOne("CRMFiloServis.Shared.Entities.Arac", "Arac")
                        .WithMany("Masraflar")
                        .HasForeignKey("AracId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CRMFiloServis.Shared.Entities.Guzergah", "Guzergah")
                        .WithMany("AracMasraflari")
                        .HasForeignKey("GuzergahId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CRMFiloServis.Shared.Entities.MasrafKalemi", "MasrafKalemi")
                        .WithMany("AracMasraflari")
                        .HasForeignKey("MasrafKalemiId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CRMFiloServis.Shared.Entities.ServisCalisma", "ServisCalisma")
                        .WithMany("ArizaMasraflari")
                        .HasForeignKey("ServisCalismaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Arac");

                    b.Navigation("Guzergah");

                    b.Navigation("MasrafKalemi");

                    b.Navigation("ServisCalisma");
                });

            modelBuilder.Entity("CRMFiloServis.Shared.Entities.BankaKasaHareket", b =>
                {
                    b.HasOne("CRMFiloServis.Shared.Entities.BankaHesap", "BankaHesap")
                        .WithMany("Hareketler")
                        .HasForeignKey("BankaHesapId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CRMFiloServis.Shared.Entities.Cari", "Cari")
                        .WithMany("BankaKasaHareketler")
                        .HasForeignKey("CariId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("BankaHesap");

                    b.Navigation("Cari");
                });

            modelBuilder.Entity("CRMFiloServis.Shared.Entities.Fatura", b =>
                {
                    b.HasOne("CRMFiloServis.Shared.Entities.Cari", "Cari")
                        .WithMany("Faturalar")
                        .HasForeignKey("CariId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cari");
                });

            modelBuilder.Entity("CRMFiloServis.Shared.Entities.FaturaKalem", b =>
                {
                    b.HasOne("CRMFiloServis.Shared.Entities.Fatura", "Fatura")
                        .WithMany("FaturaKalemleri")
                        .HasForeignKey("FaturaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fatura");
                });

            modelBuilder.Entity("CRMFiloServis.Shared.Entities.Guzergah", b =>
                {
                    b.HasOne("CRMFiloServis.Shared.Entities.Cari", "Cari")
                        .WithMany("Guzergahlar")
                        .HasForeignKey("CariId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cari");
                });

            modelBuilder.Entity("CRMFiloServis.Shared.Entities.OdemeEslestirme", b =>
                {
                    b.HasOne("CRMFiloServis.Shared.Entities.BankaKasaHareket", "BankaKasaHareket")
                        .WithMany("OdemeEslestirmeleri")
                        .HasForeignKey("BankaKasaHareketId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CRMFiloServis.Shared.Entities.Fatura", "Fatura")
                        .WithMany("OdemeEslestirmeleri")
                        .HasForeignKey("FaturaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BankaKasaHareket");

                    b.Navigation("Fatura");
                });

            modelBuilder.Entity("CRMFiloServis.Shared.Entities.ServisCalisma", b =>
                {
                    b.HasOne("CRMFiloServis.Shared.Entities.Arac", "Arac")
                        .WithMany("ServisCalismalari")
                        .HasForeignKey("AracId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CRMFiloServis.Shared.Entities.Guzergah", "Guzergah")
                        .WithMany("ServisCalismalari")
                        .HasForeignKey("GuzergahId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CRMFiloServis.Shared.Entities.Sofor", "Sofor")
                        .WithMany("ServisCalismalari")
                        .HasForeignKey("SoforId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Arac");

                    b.Navigation("Guzergah");

                    b.Navigation("Sofor");
                });

            modelBuilder.Entity("CRMFiloServis.Shared.Entities.Arac", b =>
                {
                    b.Navigation("Masraflar");

                    b.Navigation("ServisCalismalari");
                });

            modelBuilder.Entity("CRMFiloServis.Shared.Entities.BankaHesap", b =>
                {
                    b.Navigation("Hareketler");
                });

            modelBuilder.Entity("CRMFiloServis.Shared.Entities.BankaKasaHareket", b =>
                {
                    b.Navigation("OdemeEslestirmeleri");
                });

            modelBuilder.Entity("CRMFiloServis.Shared.Entities.Cari", b =>
                {
                    b.Navigation("BankaKasaHareketler");

                    b.Navigation("Faturalar");

                    b.Navigation("Guzergahlar");
                });

            modelBuilder.Entity("CRMFiloServis.Shared.Entities.Fatura", b =>
                {
                    b.Navigation("FaturaKalemleri");

                    b.Navigation("OdemeEslestirmeleri");
                });

            modelBuilder.Entity("CRMFiloServis.Shared.Entities.Guzergah", b =>
                {
                    b.Navigation("AracMasraflari");

                    b.Navigation("ServisCalismalari");
                });

            modelBuilder.Entity("CRMFiloServis.Shared.Entities.MasrafKalemi", b =>
                {
                    b.Navigation("AracMasraflari");
                });

            modelBuilder.Entity("CRMFiloServis.Shared.Entities.ServisCalisma", b =>
                {
                    b.Navigation("ArizaMasraflari");
                });

            modelBuilder.Entity("CRMFiloServis.Shared.Entities.Sofor", b =>
                {
                    b.Navigation("ServisCalismalari");
                });
#pragma warning restore 612, 618
        }
    }
}
